#!/usr/bin/env bash

set -euo pipefail

LIBYUV_TAR_URL="https://chromium.googlesource.com/libyuv/libyuv/+archive/refs/heads/stable.tar.gz"
LIBYUV_TAR_FILE="/tmp/libyuv.tar.gz"
LIBYUV_SRC_DIR="/tmp/libyuv"

prepare_source() {
  cd /tmp

  # Remove old files if they exist
  [ -f "$LIBYUV_TAR_FILE" ] && rm "$LIBYUV_TAR_FILE"
  [ -d "$LIBYUV_SRC_DIR" ] && rm -rf "$LIBYUV_SRC_DIR"

  mkdir -p "$LIBYUV_SRC_DIR"
  wget "$LIBYUV_TAR_URL" -O "$LIBYUV_TAR_FILE"
  tar -xzf "$LIBYUV_TAR_FILE" -C "$LIBYUV_SRC_DIR"
  cd "$LIBYUV_SRC_DIR"
}

build_and_install() {
  export MAKEFLAGS=-j$(nproc)

  mkdir -p build
  cd build

  cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DCMAKE_INSTALL_PREFIX=/usr

  make yuv
  install -D -m 0644 libyuv.a /usr/lib/libyuv.a

  cd ..
  cp -r include/ /usr/
}

prepare_source
build_and_install
